dist: trusty
language: c
addons:
  apt:
    sources:
      - sourceline: ppa:team-gcc-arm-embedded/ppa
    packages:
      - gcc-arm-embedded
script:
  - arm-none-eabi-gcc -v
  - make release OUT=bcf-ethernet-climate-monitor-${TRAVIS_TAG} VERSION=${TRAVIS_TAG}
deploy:
  skip_cleanup: true
  file_glob: true
  file:
    - out/release/*.bin
    - out/release/*.elf
  api_key: ${GITHUB_KEY}
  provider: releases
  overwrite: true
  on:
    tags: true
